#!/bin/sh
# Builds collab-notify.exe — the Windows toast helper — from the Mac.
# Needs the .NET SDK:  brew install dotnet
set -e
cd "$(dirname "$0")"
OUT="${1:-$PWD/../../dist.noindex/windows}"

DOTNET="$(command -v dotnet || echo /opt/homebrew/opt/dotnet/bin/dotnet)"
[ -x "$DOTNET" ] || { echo "collab: no dotnet — run: brew install dotnet" >&2; exit 1; }

export DOTNET_CLI_TELEMETRY_OPTOUT=1 DOTNET_NOLOGO=1
mkdir -p "$OUT"
"$DOTNET" publish -c Release -o "$OUT" >/dev/null
# The toast's icon; must sit beside the exe. Generated by notify/mac/build.sh,
# which is always run first by the top-level build.sh.
[ -f collab.png ] || { echo "collab: notify/windows/collab.png missing — run notify/mac/build.sh first" >&2; exit 1; }
cp collab.png "$OUT/collab.png"
rm -f "$OUT/collab-notify.pdb"
echo "built: $OUT/collab-notify.exe ($(du -h "$OUT/collab-notify.exe" | cut -f1))"
